# Generated by Django 2.1.5 on 2019-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190316_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tyalent', 'tyalent'), ('trustee', 'trustee'), ('company', 'company')], default='tyalent', max_length=20),
        ),
    ]
